on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
         with:
            # Use this username's contribution graph  
            user_name: rikoairlan
            # Text on contribution graph 
            text: WELCOME
